baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'marat-rkh homepage'
theme = 'terminal'

[[menu.main]]
name = "About"
url = "/about/"

[[menu.main]]
name = "Posts"
url = "/posts/"

[params]
contentTypeName = "posts"
centerTheme = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'